### ISSUE TITLE
AWS credentials file keys should not be case sensitive

### ISSUE THREAD

**Issue by trevorstr** [awslabs/aws-sdk-rust#1020]
### Describe the bug

The AWS SDK for Rust requires lowercase keys, such as `aws_access_key_id` instead of `AWS_ACCESS_KEY_ID`. This is inconsistent with the AWS CLI, and I'm 90% confident other SDKs don't have this limitation either.

### Expected Behavior

AWS credentials file should support case insensitive configuration keys.

### Current Behavior

AWS SDK for Rust **requires** lower-case keys in the AWS credentials file.

### Reproduction Steps

```
[default]
AWS_ACCESS_KEY_ID=asdf
AWS_SECRET_ACCESS_KEY=asdf
REGION=us-west-1
```

### Possible Solution

Make the profile file credentials chain case insensitive.

### Version

```text
rust-aws-rekognition v0.1.0 (/workspaces/rust-aws-rekognition)
├── aws-config v1.1.1
```
```


### Environment details (OS name and version, etc.)

Linux / GitHub Codespaces

### Logs

_No response_

**Comment by vemarun** [comment]
Today same case with me but this thing was highlighted by rust-analyzer.
I am not sure if this bug is in sdk or rust-analyzer enforces it that way.
`Field AWS_ACCESS_KEY_ID should have snake_case name, e.g. aws_access_key_id rust-analyzer[non_snake_case](https://doc.rust-lang.org/rustc/?search%3Dnon_snake_case)`

**Comment by rcoh** [comment]
This will be fixed in https://github.com/smithy-lang/smithy-rs/pull/3344, thanks for reporting!

**Comment by rcoh** [comment]
fixed.

**Comment by trevorstr** [comment]
@rcoh Nice, thanks
