### ISSUE TITLE
SSM GetParametersInputBuilder.names Doesn't Split Parameters

### ISSUE THREAD

**Issue by BenD0G** [awslabs/aws-sdk-rust#1150]
### Describe the bug

`GetParametersInputBuilder::names` takes a `String` as input, and just appends the string provided to `self.names`.

This means that you actually can't query for multiple parameters at the same time if you use `.names`.

Note that `.set_names` works as expected.

The AWS CLI says, for `aws ssm get-parameters help`:

`Syntax: "string" "string" ...`

It seems to me like `names()` should take something like `&[String]`.

This SDK project is awesome; keep up the great work! 😄 

### Expected Behavior

`GetParametersInputBuilder::names` should take an iterator of parameter names.

### Current Behavior

It takes a string, which is already confusing, and doesn't split the string on any delimiter.

### Reproduction Steps

```rust
let config = aws_config::defaults(BehaviorVersion::latest()).load().await;
let ssm_client = aws_sdk_ssm::Client::new(&config);

let params_result = ssm_client
    .get_parameters()
    .names("PARAM_A PARAM_B")
    .send()
    .await
    .unwrap();
```

### Possible Solution

As above, change the signature of `GetParametersInputBuilder::names`.

### Version

```text
aws-config v1.4.0
aws-sdk-ssm v1.28.0
```

### Environment details (OS name and version, etc.)

WSL2

**Comment by ysaito1001** [comment]
Hi @BenD0G, thank you for bringing this to our attention. I assume you're not blocked by this since [.set_names](https://docs.rs/aws-sdk-ssm/latest/aws_sdk_ssm/operation/delete_parameters/builders/struct.DeleteParametersInputBuilder.html#method.set_names) works for your use case?

Usually, operation methods, such as names and signatures, are derived from the original service Smithy model ([ex.  get_parameters)](https://github.com/awslabs/aws-sdk-rust/blob/main/aws-models/ssm.json#L13878-L13897). `.name`, in this case, a method [we render as a helper](https://github.com/smithy-lang/smithy-rs/blob/1ccf22db908281c1111195465e6113842a91b67a/codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/generators/BuilderGenerator.kt#L362-L386) to append an item to the underlying collection. You can see this pattern (`XXX` for appending, and `set_XXX` for overrding) in other SDK crates too ([example](https://docs.rs/aws-sdk-ec2/latest/aws_sdk_ec2/operation/describe_fpga_images/builders/struct.DescribeFpgaImagesFluentBuilder.html#method.fpga_image_ids)), which is why `.name` currently takes a single string and is meant to be used as a helper for appending.

**Comment by BenD0G** [comment]
Sorry, missed the notification! Yes you're absolutely right, apologies for the silly question 🙂
