### ISSUE TITLE
ByteStream: add support for from  impl Read + Seek

### ISSUE THREAD

**Issue by i18nsite** [awslabs/aws-sdk-rust#1183]
### Describe the feature

ByteStream: add support for  impl Read 

### Use Case

I can pipeline from one reader to s3

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by aajtodd** [comment]
Thanks for the feature request. `ByteStream` is modeled as an async API and trying to provide a sync `Read` implementation is not something we plan to support. We can't support `Seek` because not all streams are seekable. 

You can turn a `ByteStream` into `tokio::AsyncRead` (see [docs](https://docs.rs/aws-smithy-types/latest/aws_smithy_types/byte_stream/struct.ByteStream.html#method.into_async_read)). You can then maybe leverage a crate from the ecosystem to bridge the sync and async worlds ([example](https://docs.rs/tokio-util/latest/tokio_util/io/struct.SyncIoBridge.html)).


I'm going to go ahead and close this as we don't have plans to support this directly on `ByteStream`.
