### ISSUE TITLE
Don't panic when behavior-version-latest (or major version) not set

### ISSUE THREAD

**Issue by k-bx** [awslabs/aws-sdk-rust#1190]
### Describe the feature

I've deployed my program to production server and it panics because I didn't put "behavior-version-latest" in my Cargo.toml. The code that communicates with the storage is totally optional so I'm catching any "Err"-response upon connection and just log it. To my surprise, it crashed the whole runtime which is not great.

### Use Case

-

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by aajtodd** [comment]
Thanks for the feedback. This is [documented behavior](https://docs.rs/aws-sdk-s3/latest/aws_sdk_s3/struct.Client.html#method.new) but I understand that it resulted in a frustrating experience.

The recommended way to create service clients is through the `aws-config` crate, you can find documentation on creating a service client this way in the [developer guide](https://docs.aws.amazon.com/sdk-for-rust/latest/dg/creating-a-service-client.html).

I'm going to close this as it's expected behavior.
