### ISSUE TITLE
docs.rs build failed for v1.98.0

### ISSUE THREAD

**Issue by Leandros** [awslabs/aws-sdk-rust#1224]
### Describe the bug

No documentation for `latest` (as of writing) or version `1.98.0` is available on docs.rs.

![image (1)](https://github.com/user-attachments/assets/33f266fd-1d24-4627-a4e1-70542d37a520)

Old versions are available.

![image](https://github.com/user-attachments/assets/6080ec87-2320-48f0-a4e0-3bc58719d542)

This applies not only to `aws_sdk_ec2`, but also to other crates of the SDK (for example, https://docs.rs/aws-sdk-apigateway/1.53.0/aws_sdk_apigateway/)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The crates documentation is available on docs.rs

### Current Behavior

![image (1)](https://github.com/user-attachments/assets/6a34b5d0-cf00-48f3-95bd-05249b4c0faf)

### Reproduction Steps

Go to docs.rs of some of the crates of the SDK. For example:

* https://docs.rs/aws-sdk-ec2/1.98.0/aws_sdk_ec2/
* https://docs.rs/aws-sdk-apigateway/1.53.0/aws_sdk_apigateway/

### Version

```text
1.98.0
```

### Environment details (OS name and version, etc.)

-

**Comment by landonxjames** [comment]
Documentation for 1.98 is now available: https://docs.rs/aws-sdk-ec2/1.98.0/aws_sdk_ec2/

Normally when you see this it is because that version of the SDK has released recently but docs.rs hasn't yet published the new documentation. There can be several hours of lag between the crate publishing and the docs publishing.
