### ISSUE TITLE
[request]: I wish DynamoDB fluent builders implemented `Clone`

### ISSUE THREAD

**Issue by dcormier** [awslabs/aws-sdk-rust#254]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

It would help me if DynamoDB [fluent builders](https://awslabs.github.io/aws-sdk-rust/aws_sdk_dynamodb/client/fluent_builders/index.html) implemented `Clone`.

I've encountered two points where I've wanted to be able to clone fluent builders.

1. When trying to scan a table and go through all the pages.
    * It would be helpful to be able to call `.set_exclusive_start_key(...)` and clone the [`Scan`](https://awslabs.github.io/aws-sdk-rust/aws_sdk_dynamodb/client/fluent_builders/struct.Scan.html) instance before calling `.send()` to get the next page so that the `Scan` instance could be re-used to get the next page.
    * Currently, I have to build a new `Scan` instance for every page.
2. When updating many items, and you encounter errors that should be retried (`500`s, `ThrottlingException`s, etc).
    * It would be nice to be able to clone the  [UpdateItem](https://awslabs.github.io/aws-sdk-rust/aws_sdk_dynamodb/client/fluent_builders/struct.UpdateItem.html) and just retry the `.send()` call.
    * Currently, I have to build a new `UpdateItem` for every attempt.

I'm sure I will find more cases when being able to clone a struct from that module would be useful. I've only been using the SDK for two days.

**Comment by dcormier** [comment]
Eh. Less interested. I'll let someone else have it.
<img width="551" alt="image" src="https://user-images.githubusercontent.com/216265/137361502-18935d60-8f5a-49d9-99db-a7fdc0945a7b.png">

**Comment by rmbreak** [comment]
Hey I'm interested in learning and helping out. Is this something someone who has read the book and written a few toy programs could help out with? Not sure how these mentor sessions usually go :p.

**Comment by Jacco** [comment]
@rcoh 

I'd like to have a go at it :-) (Am new at rust and kotlin though).

I thought of conditionally adding the following code to `FluentClientDecorator.kt` in the `FluentClientGenerator`:

``` kotlin
                    rustTemplate(
                        """
                        /// Creates a clone from another `${operationSymbol.name}`.
                        pub fn clone_from(self, other: Self) -> Self {
                            Self { handle: self.handle.clone(), inner: other.inner.clone() }
                        }
                        """,
                    )
```

I don't know if this is how it is desired.

I also don't know how to properly make it conditional. It needs to be conditional because not all of the `inner` members of the operations in the sdk can be cloned.

Regards, Jacco

**Comment by rcoh** [comment]
did you try adding a clone bound here? https://github.com/awslabs/smithy-rs/blob/cf2034f9cf7a69d1360afa0042d2a08af2a18773/codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/smithy/generators/FluentClientDecorator.kt#L406

**Comment by Jacco** [comment]
@rcoh Yes I tried that first but many `inner` are not Clone.

**Comment by rcoh** [comment]
ah right because of `ByteStream`. You'll need to use a tactic like this: https://github.com/awslabs/smithy-rs/blob/c8a940be89ebe07200800a0d05fa58863be45b3d/codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/smithy/generators/BuilderGenerator.kt#L164-L166

That way we can generate the identical derives that `Inner` has. You can use `operationShape.inputShape(model).expectRustMetadata()` to pull the right piece of information

**Comment by Jacco** [comment]
@rcoh 

I made a PR :-) Hope it is OK.

**Comment by rcoh** [comment]
a fix will go out in the next release!
