### ISSUE TITLE
SSO credential providers

### ISSUE THREAD

**Issue by vishaalt** [awslabs/aws-sdk-rust#4]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add support for SSO credential providers

**Comment by abatkin** [comment]
Can we clarify the scope of this issue? For example, does this include SAML (`AssumeRoleWithSAML`) or should I open a dedicated feature request for that?

**Comment by jdisanti** [comment]
@abatkin - This is tracking the addition of a credential provider that retrieves temporary credentials using an SSO access token, similar to [what's in the Go v2 SDK](https://github.com/aws/aws-sdk-go-v2/blob/main/credentials/ssocreds/doc.go). You should already be able to make a call to `AssumeRoleWithSAML` [with the STS client](https://awslabs.github.io/aws-sdk-rust/aws_sdk_sts/client/struct.Client.html#method.assume_role_with_saml), and [use the result of that call to provide credentials](https://github.com/awslabs/aws-sdk-rust/blob/main/sdk/examples/sts/src/bin/credentials-provider.rs#L19), but you should open a feature request with more details about your use-case as it may make sense for the SDK to have a credential provider for it.

**Comment by abatkin** [comment]
> ...but you should open a feature request with more details about your use-case as it may make sense for the SDK to have a credential provider for it.

Perfect. For anyone else who comes across this and wonders the same thing, see also #144

**Comment by bobbyrward** [comment]
In the meantime, I've written a credential provider you can use until it comes to the sdk.
https://github.com/bobbyrward/aws-sdk-rust-sso-credentials.

**Comment by pietroalbini** [comment]
Would also love to see this implemented!

**Comment by naftulikay** [comment]
I created [naftulikay/aws-sso-env](https://github.com/naftulikay/aws-sso-env) as a stopgap solution for obtaining SSO credentials. You'll need to install Rust to compile it, follow the instructions in the repo to get things working. The general idea is that you will export credentials into your environment variables and have the AWS SDK for Rust just grab them from there, rather than using an integrated SSO provider in your code.

I don't have the time right now to flesh this out into a full credentials provider, but perhaps in the future, I will. 

Thanks to @bobbyrward above for his code, I forked it locally and got the inspiration to build a standalone utility for doing this.

**Comment by rcoh** [comment]
this has landed in main and will go out in the next release! Thanks for the upvotes everyone 🎉

**Comment by rcoh** [comment]
you can try this today by using the `next` branch as a Git dependency.

```toml
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }

# note that you'll need to switch services as well so that `aws_types::Config` is the same type from Rust's perspective:
aws-sdk-<service> = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
```

**Comment by Velfi** [comment]
landed in v0.5.2

**Comment by vfilter** [comment]
Documentation on this is really not great. It would be great if someone could provide an example of how this works. I can see that there is an sso credentials provider [here](https://docs.rs/aws-config/latest/aws_config/index.html) but I have no idea how to use it. 

Specifically, I would like to just specify the profile to use similar to boto3 `boto3.setup_default_session(profile_name='sandbox')`

**Comment by benkehoe** [comment]
@vfilter The documentation is definitely lacking. What you're looking for, I believe, is something like ([docs here](https://docs.rs/aws-config/latest/aws_config/struct.ConfigLoader.html#method.profile_name)):
```rust
use aws_config::profile::{ProfileFileCredentialsProvider, ProfileFileRegionProvider};
use aws_config::profile::profile_file::{ProfileFiles, ProfileFileKind};

let sdk_config = aws_config::from_env()
    .profile_name("sandbox")
    .load()
    .await;
```

As for boto3, I'd recommend against modifying the default session with `setup_default_session()` (and generally against using the package-level functions like `boto3.client()`), because it might conflict if different parts of your code are trying to use different credentials. Instead, use boto3 Sessions directly. [Here's an explainer on that](https://ben11kehoe.medium.com/boto3-sessions-and-why-you-should-use-them-9b094eb5ca8e).

**Comment by trevorstr** [comment]
It would be nice if there were a documentation section under the AWS Rust SDK docs ➡️ https://docs.aws.amazon.com/sdk-for-rust/latest/dg/credentials.html

It shows how to use static credentials, but that isn't a security best practice.
