### ISSUE TITLE
STS regionalized endpoints

### ISSUE THREAD

**Issue by vishaalt** [awslabs/aws-sdk-rust#40]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**
Once STS is supported, allow customers to make requests to STS regional endpoints instead of the global STS endpoint

**Additional context**
Most STS AWS public endpoints are modeled in RIP to use the sts.amazonaws.com endpoint by specifying the global endpoint within STS's defaults endpoint property of the endpoints.json. This behavior forces the SDKs to send requests to the global STS endpoint for all regions that do not explicitly have an alternate region specified.

**Comment by abatkin** [comment]
This is important for environments using VPC Endpoints for STS (particularly if they use Private DNS Names) since the default `sts.amazonaws.com` does not support Private DNS Names - but the regional endpoints do. In VPCs lacking internet access, services would be able to reach the regional STS VPC Endpointis, but not the global one.
