### ISSUE TITLE
[request]: Add Kinesis Video example

### ISSUE THREAD

**Issue by overheat** [awslabs/aws-sdk-rust#496]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

### Tell us about your request

Add Kinesis Video example.

### Tell us about the problem you're trying to solve.

Put video to cloud, then playback in web with HLS.

### Are you currently working around this issue?

No.

### Additional context

[reference code](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producersdk-cpp-write.html)

**Comment by Velfi** [comment]
Hi @overheat, thanks for creating this example. One problem, we actually need examples to be PR'd to the [docs repo](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/rust_dev_preview) because that's actually were we pull things from whenever we release new versions. Otherwise this change would get blown away whenever we release `0.10.0`. Would you mind reopening this as a PR to that repo?

**Comment by jdisanti** [comment]
Resolving this in favor of https://github.com/awsdocs/aws-doc-sdk-examples/issues/3681
