### ISSUE TITLE
Wrong link in DynamoDB's readme

### ISSUE THREAD

**Issue by NichoBrando** [awslabs/aws-sdk-rust#511]
### Describe the issue

Hello, how are you? Good evening! 😄 

I found a small mistake when I was reading the README.md for [DynamoDB](https://github.com/awslabs/aws-sdk-rust/tree/main/examples/dynamodb). There's a link that points to a wrong link for this tutorial: [Create, read, update, delete table](https://github.com/awslabs/aws-sdk-rust/blob/main/examples/dynamodb/src/bin/CRUD.rs). It should points to `https://github.com/awslabs/aws-sdk-rust/blob/main/examples/dynamodb/src/bin/crud.rs` .

### Links

https://github.com/awslabs/aws-sdk-rust/tree/main/examples/dynamodb

https://github.com/awslabs/aws-sdk-rust/blob/main/examples/dynamodb/src/bin/crud.rs

**Comment by Velfi** [comment]
Thanks for catching this. I checked and it's actually fixed in the [latest version of the docs](https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/rust_dev_preview/dynamodb/README.md), we just haven't released those changes yet. I'm actually running a release today so this should be fixed pretty soon.

**Comment by rcoh** [comment]
fixed! thanks for reporting
