### ISSUE TITLE
Add support for Textract

### ISSUE THREAD

**Issue by msuiche** [awslabs/aws-sdk-rust#723]
### Describe the feature

There is currently no official support for AWS Textract, the only way to use now is to use `rusoto_textract` which is currently unmaintained and lacks of examples. 

### Use Case

AWS Textract

### Proposed Solution

There is an initial implementation here: https://docs.rs/rusoto_textract/latest/rusoto_textract/

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by rcoh** [comment]
Does https://crates.io/crates/aws-sdk-textract not do what you need?

**Comment by msuiche** [comment]
It points to this current repository but I can't find the source code (which I would need since no code example are provided)

**Comment by rcoh** [comment]
Yeah—you're right, examples are only available for a limited number of crates. Luckily, since all the crates are generated they all follow an identical pattern:
```rust
let client = <initialize client>;

client.operation_name().param1(...).param2(...).send().await
```

Docs for the textract crate are available on docs.rs: https://docs.rs/aws-sdk-textract/0.24.0/aws_sdk_textract/
The source code is available here: https://github.com/awslabs/aws-sdk-rust/tree/main/sdk/textract

The guide for using the SDK generally is available here: https://docs.aws.amazon.com/sdk-for-rust/latest/dg/welcome.html

**Comment by Velfi** [comment]
Since we do support Textract, I'm going to close this ticket. @msuiche please open another ticket if you encounter any missing functionality or bugs and create a discussion if you run into any confusing things while working with our Textract crate.
