### ISSUE TITLE
Add Kafka and MSK examples for rust

### ISSUE THREAD

**Issue by ChaitanyaUV** [awslabs/aws-sdk-rust#803]
### Describe the feature

Can someone please add examples to the repo about utilising kafka and msk through the aws-sdk in rust ?

### Use Case

I have been trying to connect to kafka through sasl_scram and am being unable to do it and the documentation is insufficient.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by Velfi** [comment]
Hey @ChaitanyaUV. Examples are maintained by a separate team, in a separate repo. If this issue is important to you, please re-submit it to the [aws-doc-sdk-examples repo](https://github.com/awsdocs/aws-doc-sdk-examples/issues). For help with your immediate issue, I recommend starting a [discussion](https://github.com/awslabs/aws-sdk-rust/discussions) and posting a minimal example showing your code and we _(along with our community)_ can take a look.
