### ISSUE TITLE
Inconsistency in input `make_operation` receiver types in the DynamoDB SDK

### ISSUE THREAD

**Issue by declanvk** [awslabs/aws-sdk-rust#816]
### Describe the bug

The receiver type of the [`TransactWriteItemsInput::make_operation`](https://docs.rs/aws-sdk-dynamodb/latest/aws_sdk_dynamodb/operation/transact_write_items/struct.TransactWriteItemsInput.html#method.make_operation) and [`ExecuteTransactionInput::make_operation`](https://docs.rs/aws-sdk-dynamodb/latest/aws_sdk_dynamodb/operation/execute_transaction/struct.ExecuteTransactionInput.html#method.make_operation)  is `self` while all (? only checked a subset) of the other `*Input::make_operation` methods use `&self` as the receiver.

### Expected Behavior

I expected the receiver type to be consistent across all types

### Current Behavior

The receiver type was inconsistent

### Reproduction Steps

Attempt to provide a reference to the `make_operation` method

### Possible Solution

I believe that this inconsistency is because the `make_operation` method must modify the `TransactWriteItemsInput` to set an idempotency token if one is not provided, see source: https://docs.rs/aws-sdk-dynamodb/latest/src/aws_sdk_dynamodb/operation/transact_write_items.rs.html#39-42.

Similarly for the `ExecuteTransactionInput` type, which also has an idempotency token.

------

I'm not sure what the fix should be here, other than I don't think that internal mutability is a good answer. The `make_operation` method is not explicitly part of a trait, so there is no guarantee of uniform type signatures. Maybe some additional documentation on these methods would be the best fix

### Version

```text
aws-sdk-dynamodb = "0.28.0"
```

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by declanvk** [comment]
Examples of `make_operation(&self, ....`:
 - [`BatchWriteItemInput::make_operation`](https://docs.rs/aws-sdk-dynamodb/latest/aws_sdk_dynamodb/operation/batch_write_item/struct.BatchWriteItemInput.html#method.make_operation)
 - [`GetItemInput::make_operation`](https://docs.rs/aws-sdk-dynamodb/latest/aws_sdk_dynamodb/operation/get_item/struct.GetItemInput.html#method.make_operation)
 - [`TransactGetItemsInput::make_operation`](https://docs.rs/aws-sdk-dynamodb/latest/aws_sdk_dynamodb/operation/transact_get_items/struct.TransactGetItemsInput.html#method.make_operation)

**Comment by jdisanti** [comment]
I believe this is because streaming requests (e.g., S3's `PutObject`) need to take ownership of the streaming body from the input. The `make_operation` function will be going away in a future release, so we won't spend any time making it consistent.

Was this inconsistency causing a problem for you in the current SDK?

**Comment by declanvk** [comment]
> The `make_operation` function will be going away in a future release, so we won't spend any time making it consistent.

Could you point me to more information about this? Are we going to retain the ability to execute a generic operation against a custom client?

> Was this inconsistency causing a problem for you in the current SDK?

Not a particularly bad issue, I had written a macro which abstracted over multiple DynamoDB operations, but assumed that all their `*Input::make_operation` methods would always use a `&self` receiver type. Fixing it wasn't too bad

**Comment by jdisanti** [comment]
There is some information on the direction we're heading [in this doc about orchestration](https://github.com/awslabs/smithy-rs/blob/main/design/src/client/orchestrator.md).

> Are we going to retain the ability to execute a generic operation against a custom client?

Hard to say exactly without knowing more about this. What are you doing with generic operations?

**Comment by jdisanti** [comment]
Oh, I see. The good news is that what you're doing should be easier and feel more first-class after the refactor that removes `make_operation` since you'll be able to add an interceptor in config that gets called at various hook points.

For this use-case, you would be able to just add an interceptor that stores a start time in its `read_before_execution` hook (called at the very beginning of a request before anything is done), and then later records all the metrics using that start time in its `read_after_execution` hook (always called at the end of a request regardless of its success/failure).

This will allow you to use the client directly and still get the instrumentation you want.

I'm going to close this issue for now since the plan is to remove `make_operation`.
