### ISSUE TITLE
Please avoid dash in version numbers to avoid issues with packagers

### ISSUE THREAD

**Issue by glaubitz** [awslabs/aws-sdk-rust#93]
I just started working on packaging `aws-sdk-rust` for openSUSE/SLE as a small side project and noticed that upstream is using a dash in the version number to add the "alpha" prefix.

Since Linux package managers use the dash to separate upstream version and package revision numbers, the dash should not be used for versioning in upstream projects.

Could you maybe instead use `+` or `~`, e.g. `0.0.5~alpha` to avoid this issue in the future?

**Comment by mdaffin** [comment]
It is however [convention for semver](https://semver.org/#spec-item-9) for use `-alpha` or `-beta` or `-pre` for versions that are not yet stable and rust crates tend to follow semver versioning. I can [see](https://crates.io/crates/quote/versions) [lots](https://crates.io/crates/cargo-release/versions) of [examples](https://crates.io/crates/rand/versions) of other crates doing this and none that use a different convention for pre-releases.

**Comment by rcoh** [comment]
It's probably best if we avoid packaging the SDK until it's out of alpha? I don't know the implications of having the SDK packaged in openSUSE, but it really shouldn't be used as a dependency for anything other than toy projects right now. Once the SDK is out of alpha, this shouldn't be an issue since there won't be a `-alpha` on the tags anymore.

**Comment by glaubitz** [comment]
> It is however [convention for semver](https://semver.org/#spec-item-9) for use `-alpha` or `-beta` or `-pre` for versions that are not yet stable and rust crates tend to follow semver versioning. I can [see](https://crates.io/crates/quote/versions) [lots](https://crates.io/crates/cargo-release/versions) of [examples](https://crates.io/crates/rand/versions) of other crates doing this and none that use a different convention for pre-releases.

Well, that's really an unfortunate choice by the Rust community given Linux package managers have been using that scheme for a long time now.

**Comment by glaubitz** [comment]
> It's probably best if we avoid packaging the SDK until it's out of alpha? I don't know the implications of having the SDK packaged in openSUSE, but it really shouldn't be used as a dependency for anything other than toy projects right now. Once the SDK is out of alpha, this shouldn't be an issue since there won't be a `-alpha` on the tags anymore.

It was an attempt to expose the project to more users, including SLE customers in the Public Cloud which includes AWS.

**Comment by mdaffin** [comment]
> Well, that's really an unfortunate choice by the Rust community given Linux package managers have been using that scheme for a long time now.

It is not an uncommon issue for prereleases of loads of software (not just rust and not just semver things). Opensuse has [its own guidance](https://en.opensuse.org/openSUSE:Package_versioning_guidelines#Pre-Release_packages) on what you should do and it seems simply taking the upstream version (even when it uses ~) is not one of them.

This is due to how it sorts packages. You need to mung the version number into something that it will correctly sort and `0.1.0~alpha` will sort after `0.1.0` by their standards (so it will see the alpha version as newer then the actual release). So that is not an acceptable replacement either even if it does fit in the version field for RPMs.

**Comment by glaubitz** [comment]
> It is not an uncommon issue for prereleases of loads of software (not just rust and not just semver things). Opensuse has [its own guidance](https://en.opensuse.org/openSUSE:Package_versioning_guidelines#Pre-Release_packages) on what you should do.

Yes, all that involves additional work which will have to be performed by all downstream distributions having to override version numbers.

> This is due to how it sorts packages. You need to mung the version number into something that it will correctly sort. So that is not an acceptable replacement either even if it does fit in the version field for RPMs. It seems it supports `~` as a special char so replacing `-` with `~` in the RPM version should be sufficient for packaging semver packages (but this can be done in the package, not by upstream distributers).

I know how version numbers are being sorted. I'm not saying you should use a particular scheme, I merely mentioned which special characters are not allowed in version numbers by distribution package managers and it would be nice if the dash could just be avoided. Ideally, you would use `~alpha` because that sorts `0.0.6~alpha` below `0.0.6..

**Comment by joshtriplett** [comment]
@glaubitz Rust uses the [semver spec](https://semver.org/), which specifically requires the use of a hyphen for a pre-release. Please don't bug individual Rust crate developers when their crates are following Rust conventions which themselves follow established standards. If a packaging format wants to use version numbers that aren't the same as semver (which is perfectly fine), it's the job of packaging tools for that package format to translate version numbers accordingly.

**Comment by glaubitz** [comment]
>  Rust uses the semver spec, which specifically requires the use of a hyphen for a pre-release. Please don't bug individual Rust crate developers when their crates are following Rust conventions which themselves follow established standards.

Why should I not be allowed to complain about versioning when it's compatible with packaging?

> If a packaging format wants to use version numbers that aren't the same as semver (which is perfectly fine), it's the job of packaging tools for that package format to translate version numbers accordingly from semver to that packaging format's versioning system.

The versioning scheme of package managers has existed long before Rust even existed. The Rust community could have maybe chosen a versioning scheme which doesn't pose additional burden on downstream package managers. And, no one has to use `alpha` or `beta` version suffixes, it's perfectly fine to just use a plain and simple version.

All I wanted to do is expose the AWS Rust SDK to more potential cloud customers. If there is no interest from the upstream project in this regard, I'm fine with that.

**Comment by mdaffin** [comment]
> > If a packaging format wants to use version numbers that aren't the same as semver (which is perfectly fine), it's the job of packaging tools for that package format to translate version numbers accordingly from semver to that packaging format's versioning system.
> 
> The versioning scheme of package managers has existed long before Rust even existed. The Rust community could have maybe chosen a versioning scheme which doesn't pose additional burden on downstream package managers. And, no one has to use `alpha` or `beta` version suffixes, it's perfectly fine to just use a plain and simple version.

Semver existed before rust and is a widely used versioning standard use by more software packages than any other version format (are there even any other well established formats?). Most programming package managers use it or at least encourage its use. This includes [npm packages](https://docs.npmjs.com/about-semantic-versioning) and [ruby gems](https://guides.rubygems.org/patterns/#semantic-versioning). And [python recommend just using a `.`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#pre-release-versioning) but that screws up the sorting on RPM packages so you cannot just take those versions verbatim either. And quite a few python packages also follow semver.

Versioning in general is a mess. Semver adds some consistency across everything that uses it and actually creates a standard around what should be used when.

In contrast distro packaging systems use all sorts of different rules for what is allowed and what is not, what makes a prerelease package etc... Maybe packagers should adopt the semver standard rather than each coming up with there own. But that is not likely to change. Nor is rust or python or npm or any other language or its libraries that currently uses semver is going to move away from it.

You will never get every project out there that you need to package to conform to your distros versioning requirements. Your best option is to follow your packaging formats guide lines and do the replacement yourself. Or wait for an actual release where the issue goes away.

> All I wanted to do is expose the AWS Rust SDK to more potential cloud customers. If there is no interest from the upstream project in this regard, I'm fine with that.

It is nice to see you are trying to promote the library. But I honestly don't see how an OpenSUSE package will affect this at all. People using this library will just use it from crates.io, like every other rust crate, as that is how rust developers work (just like python developers get stuff from pip and node developers get stuff from npm).

Rarely do developers think _oh, lets see if some package is supported by this distro_ for languages that include their own package repos. Quite often they ignore what the distro provides and use the versions from the languages repo any way (which are always far more up to date then a repos versions).

It is only when OpenSUSE wants to package something someone has created that you need to worry about packaging this library in what ever way OpenSUSE needs.

I am not trying to discourage you from packaging this or anything else. But you are going to need to make concessions with what is possible or likely to happen. Here changing the version for pre-release to use a `~` in the OpenSUSE package is not a big ask for a distro packager to do. It is a much smaller concession than asking every software package that uses semver to not follow that well established conversion for versioning software.

**Comment by jdisanti** [comment]
We stopped appending `-alpha` to the version numbers back in December. I think it's safe to close this issue.
