### ISSUE TITLE
Instance metadata credentials support

### ISSUE THREAD

**Issue by dialtone** [awslabs/aws-sdk-rust#97]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by twitu** [comment]
I'd love to work on this. I'll mostly be scratching my own itch since I often run code on an EC2 without creating a different set of user credentials.

I've take a look at the code base and I think this will need one more type of credential provider, something like `InstanceMetadataCredentialsProvider` that implements the `ProviderCredentials` trait.

This will require two inputs -
1. Role name attached to the instance
2. Default region to set

The provider logic will have to query instance metadata url `http://169.254.169.254/latest/meta-data/iam/security-credentials/<role-name>/`, retrieve the values and create the credentials object from it.

Please let me know if you have any guidance or concerns related to this.

**Comment by twitu** [comment]
There's also this middle ground where the user might want to use Instance metadata to retrieve credentials. But set this up as an environment credentials through a config file as [given here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-metadata.html).

In this case the logic behind retrieving the credentials (either from environment variables or from instance metadata) will have to inferred at runtime by checking if `credential_source = Ec2InstanceMetadata` is set.

**Comment by joshtriplett** [comment]
You can get the region from the instance metadata via ` placement/region`; that seems like a good default.

**Comment by joshtriplett** [comment]
Also, it should be possible to determine the role name automatically as well.

**Comment by rcoh** [comment]
IMDS credentials support has landed and will go out in the next release. Thanks for the upvotes and the patience!

**Comment by jdisanti** [comment]
IMDS credentials landed with [`v0.0.19-alpha`](https://github.com/awslabs/aws-sdk-rust/releases/tag/v0.0.19-alpha).
